name: Terraform Infra

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform Action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

permissions:
  contents: read
  actions: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init

      # 🔥 APPLY
      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          echo "🚀 Running Terraform Apply..."
          terraform apply -auto-approve -var="key_name=${{ secrets.EC2_KEY_NAME }}"

      # 🔥 DESTROY
      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          echo "🔥 Running Terraform Destroy..."
          terraform destroy -auto-approve -var="key_name=${{ secrets.EC2_KEY_NAME }}"

      # ✅ ONLY RUN THESE AFTER APPLY
      - name: Show EC2 Public IP
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform output public_ip

      - name: Capture EC2 IP
        if: ${{ github.event.inputs.action == 'apply' }}
        id: tf_output
        run: |
          echo "ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT

      - name: Update EC2_HOST Secret
        if: ${{ github.event.inputs.action == 'apply' }}
        uses: gliech/create-github-secret-action@v1
        with:
          name: EC2_HOST
          value: ${{ steps.tf_output.outputs.ip }}
          pa_token: ${{ secrets.APP_GITHUB_TOKEN }}